version: '3.4'

services: 

  users:
    container_name: users
    build: 
      context: ./services/users
      dockerfile: Dockerfile-prod
    #volumes: 
    # - './services/users:/usr/src/app'
    expose:
      - "5000"
    environment: 
      - FLASK_APP=manage.py
      - FLASK_DEBUG=1
      - FLASK_CONFIG=production
      - DATABASE_URI=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URI=postgres://postgres:postgres@users-db:5432/users_test
      - PROD_DATABASE=postgres://postgres:postgres@users-db:5432/users_prod
    depends_on: 
      - users-db
    links: 
      - users-db

  users-db:
    container_name: users-db
    build: 
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports: 
      - 5435:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  nginx:
    container_name: nginx
    build: 
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 80:80
    depends_on: 
      - users


      
      #python ./services/users/manage.py run -h 0.0.0.0

      # Creates a container named users 
      #rem:::::Directories are relative to docker-compose-dev.yml
