FROM python:3.8

# install environment dependencies

RUN apt-get update -yqq \
&& apt-get install -yqq --no-install-recommends \
netcat \
&& apt-get -q clean

# set the working directory

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements

COPY requirements.txt /usr/src/app/requirements.txt

# install requirements 

RUN pip3 install -r requirements.txt

# add entrypoint.sh

COPY entrypoint-prod.sh /usr/src/app/entrypoint.sh

# add app

COPY . /usr/src/app

# set stopsignal to sigterm

STOPSIGNAL SIGTERM

# run server

CMD ["./entrypoint-prod.sh"]